import { HardhatRuntimeEnvironment } from "hardhat/types";
import { DeployFunction } from "hardhat-deploy/types";
import fs from "fs";
import path from "path";

const deployEquiShield: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployments, getNamedAccounts, network, ethers } = hre;
  const { deploy } = deployments;
  const { deployer } = await getNamedAccounts();

  console.log(`\nDeploying EquiShield to ${network.name}...`);
  console.log(`Deployer: ${deployer}`);

  const balance = await ethers.provider.getBalance(deployer);
  console.log(`Deployer balance: ${ethers.formatEther(balance)} ETH`);

  const result = await deploy("EquiShield", {
    from: deployer,
    args: [],
    log: true,
    waitConfirmations: network.name === "sepolia" ? 5 : 1,
  });

  console.log(`\nEquiShield deployed to: ${result.address}`);
  console.log(`Transaction hash: ${result.transactionHash}`);

  // Write contract address to frontend lib
  const contractLibPath = path.join(
    __dirname,
    "../../../artifacts/equishield/src/lib/contract.ts"
  );
  const contractContent = `// Auto-generated by deploy script — do not edit manually
export const EQUISHIELD_ADDRESS = "${result.address}" as const;
export const EQUISHIELD_CHAIN_ID = ${network.config.chainId ?? 11155111};
export const DEPLOY_TX_HASH = "${result.transactionHash ?? ""}";
export const NETWORK_NAME = "${network.name}";
`;
  fs.writeFileSync(contractLibPath, contractContent);
  console.log(`Contract address written to frontend: ${contractLibPath}`);

  // Copy ABI to frontend
  const artifactsPath = path.join(
    __dirname,
    "../artifacts/contracts/EquiShield.sol/EquiShield.json"
  );
  if (fs.existsSync(artifactsPath)) {
    const abi = JSON.parse(fs.readFileSync(artifactsPath, "utf8"));
    const abiOutputPath = path.join(
      __dirname,
      "../../../artifacts/equishield/src/abi/EquiShield.json"
    );
    fs.writeFileSync(abiOutputPath, JSON.stringify(abi.abi, null, 2));
    console.log(`ABI copied to frontend: ${abiOutputPath}`);
  }
};

deployEquiShield.tags = ["EquiShield"];
export default deployEquiShield;
