// Auto-generated by deploy script — do not edit manually
export const EQUISHIELD_ADDRESS = "0x2E630632415338A37d95bFF009f8667C2D090FA7" as const;
export const EQUISHIELD_CHAIN_ID = 11155111;
export const DEPLOY_TX_HASH = "0x369cd591b0de08f2e192da0a93de1378d7867fb7c9a902eb66c72f4bf12f391b";
export const NETWORK_NAME = "sepolia";
