/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EquiShieldInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getMyShares"
      | "getMyVestedShares"
      | "getShareholderAt"
      | "getShareholderCount"
      | "grantRegulator"
      | "hasVoted"
      | "isActiveShareholder"
      | "issueShares"
      | "owner"
      | "regulator"
      | "regulatorView"
      | "shareholderList"
      | "shareholders"
      | "transferShares"
      | "vestShares"
      | "vote"
      | "votes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RegulatorGranted"
      | "SharesIssued"
      | "SharesTransferred"
      | "SharesVested"
      | "Voted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyVestedShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getShareholderAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getShareholderCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRegulator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveShareholder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueShares",
    values: [AddressLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "regulator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "regulatorView",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shareholderList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shareholders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferShares",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestShares",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyVestedShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShareholderAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShareholderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantRegulator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isActiveShareholder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "regulator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "regulatorView",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shareholderList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shareholders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vestShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;
}

export namespace RegulatorGrantedEvent {
  export type InputTuple = [regulatorAddr: AddressLike];
  export type OutputTuple = [regulatorAddr: string];
  export interface OutputObject {
    regulatorAddr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesIssuedEvent {
  export type InputTuple = [holder: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [holder: string, timestamp: bigint];
  export interface OutputObject {
    holder: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesTransferredEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, timestamp: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesVestedEvent {
  export type InputTuple = [holder: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [holder: string, timestamp: bigint];
  export interface OutputObject {
    holder: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [proposalId: BigNumberish, voter: AddressLike];
  export type OutputTuple = [proposalId: bigint, voter: string];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EquiShield extends BaseContract {
  connect(runner?: ContractRunner | null): EquiShield;
  waitForDeployment(): Promise<this>;

  interface: EquiShieldInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getMyShares: TypedContractMethod<[], [string], "view">;

  getMyVestedShares: TypedContractMethod<[], [string], "view">;

  getShareholderAt: TypedContractMethod<[i: BigNumberish], [string], "view">;

  getShareholderCount: TypedContractMethod<[], [bigint], "view">;

  grantRegulator: TypedContractMethod<
    [_regulator: AddressLike],
    [void],
    "nonpayable"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isActiveShareholder: TypedContractMethod<
    [holder: AddressLike],
    [boolean],
    "view"
  >;

  issueShares: TypedContractMethod<
    [
      holder: AddressLike,
      inputShares: BytesLike,
      proof: BytesLike,
      inputPrice: BytesLike,
      priceProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  regulator: TypedContractMethod<[], [string], "view">;

  regulatorView: TypedContractMethod<
    [holder: AddressLike],
    [
      [string, string, string] & {
        encShares: string;
        encVestedShares: string;
        encPrice: string;
      }
    ],
    "nonpayable"
  >;

  shareholderList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  shareholders: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, boolean] & {
        holder: string;
        encryptedShares: string;
        encryptedVestedShares: string;
        encryptedPricePerShare: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  transferShares: TypedContractMethod<
    [to: AddressLike, inputAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  vestShares: TypedContractMethod<
    [holder: AddressLike, inputVestedAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [proposalId: BigNumberish, inputWeight: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  votes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyShares"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyVestedShares"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getShareholderAt"
  ): TypedContractMethod<[i: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getShareholderCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRegulator"
  ): TypedContractMethod<[_regulator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActiveShareholder"
  ): TypedContractMethod<[holder: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueShares"
  ): TypedContractMethod<
    [
      holder: AddressLike,
      inputShares: BytesLike,
      proof: BytesLike,
      inputPrice: BytesLike,
      priceProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "regulator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "regulatorView"
  ): TypedContractMethod<
    [holder: AddressLike],
    [
      [string, string, string] & {
        encShares: string;
        encVestedShares: string;
        encPrice: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shareholderList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "shareholders"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, boolean] & {
        holder: string;
        encryptedShares: string;
        encryptedVestedShares: string;
        encryptedPricePerShare: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferShares"
  ): TypedContractMethod<
    [to: AddressLike, inputAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vestShares"
  ): TypedContractMethod<
    [holder: AddressLike, inputVestedAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [proposalId: BigNumberish, inputWeight: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "votes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;

  getEvent(
    key: "RegulatorGranted"
  ): TypedContractEvent<
    RegulatorGrantedEvent.InputTuple,
    RegulatorGrantedEvent.OutputTuple,
    RegulatorGrantedEvent.OutputObject
  >;
  getEvent(
    key: "SharesIssued"
  ): TypedContractEvent<
    SharesIssuedEvent.InputTuple,
    SharesIssuedEvent.OutputTuple,
    SharesIssuedEvent.OutputObject
  >;
  getEvent(
    key: "SharesTransferred"
  ): TypedContractEvent<
    SharesTransferredEvent.InputTuple,
    SharesTransferredEvent.OutputTuple,
    SharesTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SharesVested"
  ): TypedContractEvent<
    SharesVestedEvent.InputTuple,
    SharesVestedEvent.OutputTuple,
    SharesVestedEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;

  filters: {
    "RegulatorGranted(address)": TypedContractEvent<
      RegulatorGrantedEvent.InputTuple,
      RegulatorGrantedEvent.OutputTuple,
      RegulatorGrantedEvent.OutputObject
    >;
    RegulatorGranted: TypedContractEvent<
      RegulatorGrantedEvent.InputTuple,
      RegulatorGrantedEvent.OutputTuple,
      RegulatorGrantedEvent.OutputObject
    >;

    "SharesIssued(address,uint256)": TypedContractEvent<
      SharesIssuedEvent.InputTuple,
      SharesIssuedEvent.OutputTuple,
      SharesIssuedEvent.OutputObject
    >;
    SharesIssued: TypedContractEvent<
      SharesIssuedEvent.InputTuple,
      SharesIssuedEvent.OutputTuple,
      SharesIssuedEvent.OutputObject
    >;

    "SharesTransferred(address,address,uint256)": TypedContractEvent<
      SharesTransferredEvent.InputTuple,
      SharesTransferredEvent.OutputTuple,
      SharesTransferredEvent.OutputObject
    >;
    SharesTransferred: TypedContractEvent<
      SharesTransferredEvent.InputTuple,
      SharesTransferredEvent.OutputTuple,
      SharesTransferredEvent.OutputObject
    >;

    "SharesVested(address,uint256)": TypedContractEvent<
      SharesVestedEvent.InputTuple,
      SharesVestedEvent.OutputTuple,
      SharesVestedEvent.OutputObject
    >;
    SharesVested: TypedContractEvent<
      SharesVestedEvent.InputTuple,
      SharesVestedEvent.OutputTuple,
      SharesVestedEvent.OutputObject
    >;

    "Voted(uint256,address)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
  };
}
